modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="therazorhail_mod"
version="1.0.0"
displayName="TheRazorHail Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://bit.ly/3x8X4oc"
logoFile="logo.png"
authors="tom the bartender"
description='''
A mod made for Butter Boy Razor's server. This version of the mod is  called TheHeavyUpdate.
'''

[[dependencies.therazorhail_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




